# Important! Commas cannot come after the last json entry

### Register a user
POST http://localhost:1322/auth/register
Content-Type: application/json

{
  "username": "arpie",
  "password": "password"
}

### Log in a user
POST http://localhost:1322/auth/login
Content-Type: application/json

{
  "username": "arpie",
  "password": "password"
}

### Log in using invalid credentials
POST http://localhost:1322/auth/login
Content-Type: application/json

{
  "username": "arpie",
  "password": "wrongPassword!"
}

### Create a new study set
POST http://localhost:1322/studySet
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODk1MjAyLCJleHAiOjE3Mzg5ODE2MDJ9.dEXf37Q49mYMebOhR3Oq9cdtLmjRUHIiHxwj1qqfnd4
Content-Type: application/json

{
  "title": "Biology",
  "isPublic": true
}

### Delete a study set
DELETE http://localhost:1322/studySet/17
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODg4OTQyLCJleHAiOjE3Mzg5NzUzNDJ9.xbMBdAp-hs26f7poS4FnAkOxnrfp9jhSh3yfwMI9h2w

### Change the name of a study set
PUT http://localhost:1322/studySet/18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODg4OTQyLCJleHAiOjE3Mzg5NzUzNDJ9.xbMBdAp-hs26f7poS4FnAkOxnrfp9jhSh3yfwMI9h2w
Content-Type: application/json

{
  "title": "Computer Science"
}

### Change the visibility of a study set
PUT http://localhost:1322/studySet/18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODc4NTE5LCJleHAiOjE3Mzg5NjQ5MTl9.AqkaNPH7-62Pls8SkDkhmdVVnt2742_r1SdcnyfNi7g
Content-Type: application/json

{
  "isPublic": true
}

### Create a new card
POST http://localhost:1322/card/19
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODc4NTE5LCJleHAiOjE3Mzg5NjQ5MTl9.AqkaNPH7-62Pls8SkDkhmdVVnt2742_r1SdcnyfNi7g
Content-Type: application/json

{
  "question": "What does BFS stand for?",
  "answer": "Breadth First Search"
}

### Edit the (question / answer) of a card
PUT http://localhost:1322/card/23
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODk1MjAyLCJleHAiOjE3Mzg5ODE2MDJ9.dEXf37Q49mYMebOhR3Oq9cdtLmjRUHIiHxwj1qqfnd4
Content-Type: application/json

{
  "question": "Who is the current US President?",
  "answer": "Donald Trump"
}

### Edit the (isComplete) of a card
PUT http://localhost:1322/card/18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODc4NTE5LCJleHAiOjE3Mzg5NjQ5MTl9.AqkaNPH7-62Pls8SkDkhmdVVnt2742_r1SdcnyfNi7g
Content-Type: application/json

{
  "isComplete": true
}

### Delete a card
DELETE http://localhost:1322/card/22
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODk1MjAyLCJleHAiOjE3Mzg5ODE2MDJ9.dEXf37Q49mYMebOhR3Oq9cdtLmjRUHIiHxwj1qqfnd4


### Get a study set
GET http://localhost:1322/studySet/27
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODk1MjAyLCJleHAiOjE3Mzg5ODE2MDJ9.dEXf37Q49mYMebOhR3Oq9cdtLmjRUHIiHxwj1qqfnd4
Content-Type: application/json

### Get all cards from a study set
GET http://localhost:1322/studySet/18/cards
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODc4NTE5LCJleHAiOjE3Mzg5NjQ5MTl9.AqkaNPH7-62Pls8SkDkhmdVVnt2742_r1SdcnyfNi7g

### Get all sets from a user
GET http://localhost:1322/user/sets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODk1MjAyLCJleHAiOjE3Mzg5ODE2MDJ9.dEXf37Q49mYMebOhR3Oq9cdtLmjRUHIiHxwj1qqfnd4


### arpie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODk1MjAyLCJleHAiOjE3Mzg5ODE2MDJ9.dEXf37Q49mYMebOhR3Oq9cdtLmjRUHIiHxwj1qqfnd4
### arpie1: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM4ODc4NTE5LCJleHAiOjE3Mzg5NjQ5MTl9.AqkaNPH7-62Pls8SkDkhmdVVnt2742_r1SdcnyfNi7g
### arpie2: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM4ODk1MjE3LCJleHAiOjE3Mzg5ODE2MTd9.R-2CLRcSeZ2bKWlrQ7lWNdlXHOoDa0BjsoJAEdJrZWA
